### ISSUE TITLE
Packages folder maybe?

### ISSUE THREAD

**Issue by julielerman** [snehansh/EFCore_GettingStarted#1]
I spent (you don't want to know how much) time trying to build this but because your nuget pakages are in a different folder on your system than mine, I could not get VS to find ANY packages. ![image](https://user-images.githubusercontent.com/5007120/62871153-ead87680-bce8-11e9-8018-319d888848c2.png)

I got lots of ideas on twitter after trying lots of other ideas on google, but still couldn't get it sorted out (https://twitter.com/julielerman/status/1160583833638572034).  I even tried using referencepath to override the hintpaths in the csproj. I don't want to manually edit every one. Gitignore for VS intentionally removes the packages folder but keeps the packages/build folder. (I've never even explored these things before...)  Always a learning experience though. Any chance you cleaned that out before pushing?

**Comment by snehansh** [comment]
Not sure, what the issue. Thanks for taking time to look into my issue. 
Btw I was able to view the logs for the EF core queries. 
I was looking for logs at the wrong place.
I was looking in Output->Debug, but I should have looked in the Console instead.
